'use strict';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const C=window.VIBRA_CONFIG||{},ready=C.supabaseUrl&&!C.supabaseUrl.includes('TU-')&&C.publishableKey&&!C.publishableKey.startsWith('TU_');
const db=ready?window.supabase.createClient(C.supabaseUrl,C.publishableKey):null;
let session=null,admin=false,currentView='catalog',cart=[],config={},editing=null,selectedMedia=[];
const money=n=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(Number(n)||0);
const ICONS=['♥','♡','✦','✧','♛','♢','❀','✿','🌹','💋','💝','🎀','👙','🩷','💜','🖤','✨','🛍️','🧴','🪷','🕯️','🧖','💆','🛏️','🔞','📍','🏨','💍','🧸','🎁'];
const schemas={
 products:{title:'Productos',cols:['name','price','stock','active','featured','icon'],form:{name:'text',description:'textarea',sku:'text',price:'number',stock:'number',category_id:'categories',icon:'icons',active:'check',featured:'check'},media:true},
 categories:{title:'Categorías',cols:['name','slug','icon','active'],form:{name:'text',slug:'text',icon:'icons',sort_order:'number',active:'check'}},
 practitioners:{title:'Masajistas',cols:['display_name','active'],form:{display_name:'text',bio:'textarea',active:'check'},media:true},
 rooms:{title:'Habitaciones',cols:['name','active'],form:{name:'text',description:'textarea',active:'check'}},
 services:{title:'Servicios',cols:['name','hourly_price','active'],form:{name:'text',description:'textarea',hourly_price:'number',active:'check'}},
 reviews:{title:'Opiniones',cols:['rating','body','status'],readonly:true},
 coupons:{title:'Cupones',cols:['code','percent_off','used_count','max_uses','active'],form:{code:'text',percent_off:'number',max_uses:'number',expires_at:'datetime-local',active:'check'}},
 orders:{title:'Pedidos',cols:['id','total','status','payment_status','created_at'],readonly:true},
 reservations:{title:'Reservaciones',cols:['id','starts_at','ends_at','status','payment_status'],readonly:true},
 payment_proofs:{title:'Revisión de pagos',cols:['id','order_id','reservation_id','review_status'],readonly:true},
 profiles:{title:'Clientes',cols:['id','full_name','phone','created_at'],readonly:true},
 user_blocks:{title:'Bloqueos',cols:['user_id','reason','blocked_at'],form:{user_id:'text',reason:'text'}},
 site_notifications:{title:'Notificaciones',cols:['title','body','created_at'],form:{user_id:'text',title:'text',body:'textarea'}},
 conversations:{title:'Seguimiento / Chats',cols:['id','customer_id','status'],readonly:true},
 ticket_settings:{title:'Diseño de ticket',singleton:true,form:{heading:'text',footer:'textarea',show_phone:'check',show_address:'check'}},
 brand_settings:{title:'Perfil, redes y personalización',singleton:true,form:{tagline:'text',description:'textarea',hero_title:'text',primary_color:'color',accent_color:'color',theme:'theme',social_links:'json',latitude:'number',longitude:'number',business_hours:'json'}},
 business_settings:{title:'Negocio y horarios',singleton:true,form:{business_name:'text',phone:'text',email:'text',address:'text',timezone:'text',opening_time:'time',closing_time:'time',booking_min_notice_minutes:'number'}},
 site_options:{title:'Opciones, mapa y suscripción',cols:['key','value'],form:{key:'text',value:'json'}},
 staff_roles:{title:'Usuarios y permisos',cols:['user_id','role'],readonly:true},
 site_subscriptions:{title:'Suscripciones',cols:['site_name','plan_name','status','renewal_at'],readonly:true}
};
function toast(msg){const el=document.createElement('div');el.className='notice';el.textContent=msg;document.body.append(el);Object.assign(el.style,{position:'fixed',bottom:'20px',right:'20px',zIndex:99,maxWidth:'380px'});setTimeout(()=>el.remove(),6000)}
function modal(title,html){$('modalTitle').textContent=title;$('modalBody').innerHTML=html;$('modal').classList.remove('hidden')}
function hideModal(){$('modal').classList.add('hidden')}
async function query(table,select='*',limit=100){if(!db)throw Error('Configura config.js primero');const {data,error}=await db.from(table).select(select).limit(limit);if(error)throw error;return data||[]}
async function authUpdate(){if(!db)return;const r=await db.auth.getSession();session=r.data.session;admin=false;if(session){const p=await db.from('staff_roles').select('role').eq('user_id',session.user.id).maybeSingle();admin=['admin','manager'].includes(p.data?.role||'');if(p.error)console.warn('Consulta de rol:',p.error.message)}$('adminBtn').hidden=!admin;$('notifyBtn').hidden=!session;$('accountBtn').textContent=session?'Mi cuenta':'Ingresar';}
async function account(){if(!db){modal('Configuración pendiente','<p>Coloca la URL y la clave pública de Supabase en <code>config.js</code>.</p>');return}if(session){modal('Mi cuenta',`<p>${esc(session.user.email)}</p><button id="logout">Cerrar sesión</button>`);$('logout').onclick=async()=>{await db.auth.signOut();hideModal();await authUpdate()};return}modal('Ingresar / registrarse',`<div class="fields"><label>Correo<input id="mail" type="email"></label><label>Contraseña<input id="pass" type="password"></label></div><div class="row"><button id="login">Ingresar</button><button id="signup" class="secondary">Crear cuenta</button><button id="google" class="secondary">Google</button></div><p class="muted">Para administrar debes tener un rol autorizado en staff_roles.</p>`);
 $('login').onclick=async()=>{const {error}=await db.auth.signInWithPassword({email:$('mail').value,password:$('pass').value});if(error)toast(error.message);else{hideModal();await authUpdate();show(currentView)}};
 $('signup').onclick=async()=>{const{error}=await db.auth.signUp({email:$('mail').value,password:$('pass').value});toast(error?.message||'Revisa tu correo para confirmar la cuenta')};
 $('google').onclick=async()=>{const{error}=await db.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin+location.pathname}});if(error)toast(error.message)};
}
function productGallery(media){return `<div class="gallery">${media.map(m=>m.media_type==='video'?`<video controls preload="metadata" src="${esc(db.storage.from(m.bucket).getPublicUrl(m.object_path).data.publicUrl)}"></video>`:`<img loading="lazy" src="${esc(db.storage.from(m.bucket).getPublicUrl(m.object_path).data.publicUrl)}">`).join('')}</div>`}
async function catalog(){const host=$('content');host.innerHTML='<h2>Boutique +18</h2><p>Cargando catálogo…</p>';try{const [items,media,cats]=await Promise.all([query('products'),query('product_media', '*',500),query('categories')]);host.innerHTML=`<h2>Boutique para adultos</h2><div class="toolbar"><input id="search" placeholder="Buscar productos"><select id="cat"><option value="">Todas las categorías</option>${cats.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('')}</select></div><div id="productGrid" class="grid"></div>`;function draw(){const term=$('search').value.toLowerCase(),cat=$('cat').value;$('productGrid').innerHTML=items.filter(p=>p.active&&(!cat||p.category_id===cat)&&p.name.toLowerCase().includes(term)).map(p=>`<article class="card"><div style="font-size:36px">${esc(p.icon||'💝')}</div>${productGallery(media.filter(m=>m.product_id===p.id).slice(0,8))}<h3>${esc(p.name)}</h3><p class="muted">${esc(p.description)}</p><div class="row"><strong class="price">${money(p.price)}</strong><span>Stock ${p.stock}</span></div><button data-add="${p.id}">Añadir al carrito</button></article>`).join('')||'<p>No hay productos publicados.</p>';$('productGrid').querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{const p=items.find(x=>x.id===b.dataset.add);const old=cart.find(x=>x.id===p.id);if(old)old.quantity++;else cart.push({...p,quantity:1});$('cartCount').textContent=cart.reduce((n,x)=>n+x.quantity,0);toast('Agregado al carrito')})};$('search').oninput=draw;$('cat').onchange=draw;draw()}catch(e){host.innerHTML=`<div class="notice">${esc(e.message)}</div>`}}
async function bookings(){const host=$('content');host.innerHTML='<h2>Reservar masaje</h2>';try{const [services,people,rooms]=await Promise.all([query('services'),query('practitioners'),query('rooms')]);host.innerHTML+=`<div class="panel"><div class="fields"><label>Servicio<select id="svc">${services.filter(s=>s.active).map(s=>`<option value="${s.id}">${esc(s.name)} · ${money(s.hourly_price)}/h</option>`).join('')}</select></label><label>Masajista<select id="person">${people.filter(s=>s.active).map(s=>`<option value="${s.id}">${esc(s.display_name)}</option>`).join('')}</select></label><label>Habitación<select id="room">${rooms.filter(s=>s.active).map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select></label><label>Fecha y hora<input id="start" type="datetime-local"></label><label>Duración<select id="mins"><option value="30">30 minutos</option><option value="60" selected>60 minutos</option><option value="90">90 minutos</option><option value="120">120 minutos</option></select></label><label>Nombre<input id="contact" required></label><label>Teléfono<input id="phone" required></label></div><label><input type="checkbox" id="terms"> Comprendo que el tiempo comienza a la hora reservada, incluso si llego tarde. Se aplicarán las condiciones de cancelación y reembolso conforme a la legislación vigente.</label><p><button id="bookNow">Solicitar reserva</button></p></div>`;$('bookNow').onclick=async()=>{if(!session)return account();if(!$('terms').checked)return toast('Debes aceptar las condiciones');const d=await db.rpc('create_reservation',{p_service_id:$('svc').value,p_practitioner_id:$('person').value,p_room_id:$('room').value,p_starts_at:new Date($('start').value).toISOString(),p_duration_minutes:+$('mins').value,p_contact_name:$('contact').value,p_contact_phone:$('phone').value,p_accept_terms:true});toast(d.error?.message||'Reserva creada: '+d.data)}}catch(e){toast(e.message)}}
async function reviews(){const rows=await query('reviews');$('content').innerHTML=`<h2>Opiniones</h2><div class="grid">${rows.filter(x=>x.status==='published').map(r=>`<div class="card">${'★'.repeat(r.rating)}<p>${esc(r.body)}</p></div>`).join('')}</div><div class="panel"><h3>Dejar una opinión</h3><label>Calificación<select id="rating">${[1,2,3,4,5].map(i=>`<option>${i}</option>`).join('')}</select></label><label>Tu opinión<textarea id="reviewBody"></textarea></label><button id="reviewSend">Enviar para moderación</button></div>`;$('reviewSend').onclick=async()=>{if(!session)return account();const {error}=await db.from('reviews').insert({user_id:session.user.id,rating:+$('rating').value,body:$('reviewBody').value});toast(error?.message||'Opinión enviada')}}
async function contact(){const [business,mapOpts]=await Promise.all([query('business_settings'),query('site_options')]);const b=business[0]||{},opt=mapOpts.find(x=>x.key==='map')?.value||{};$('content').innerHTML=`<h2>Contacto y ubicación</h2><div class="panel"><p>${esc(b.business_name||'VibraErótica')}</p><p>${esc(b.address||'Dirección por configurar')}</p><p>${esc(b.phone||'')}</p><p>Horario: ${esc(b.opening_time)} – ${esc(b.closing_time)}</p><div id="map"></div></div>`;if(window.L){const map=L.map('map').setView([opt.lat||19.1738,opt.lng||-96.1342],opt.zoom||13);L.tileLayer(opt.style||'https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png',{attribution:'© OpenStreetMap © CARTO'}).addTo(map);L.marker([opt.lat||19.1738,opt.lng||-96.1342]).addTo(map).bindPopup(esc(opt.label||'VibraErótica'))}}
async function history(){if(!session)return account();const [orders,res]=await Promise.all([db.from('orders').select('*').order('created_at',{ascending:false}),db.from('reservations').select('*').order('starts_at',{ascending:false})]);$('content').innerHTML=`<h2>Mis compras y reservas</h2><div class="panel"><h3>Pedidos</h3>${(orders.data||[]).map(x=>`<p>${esc(x.id)} · ${money(x.total)} · ${esc(x.status)}</p>`).join('')||'Sin pedidos'}<h3>Reservas</h3>${(res.data||[]).map(x=>`<p>${new Date(x.starts_at).toLocaleString()} · ${esc(x.status)}</p>`).join('')||'Sin reservas'}</div>`}
async function show(view){currentView=view;try{if(!db){$('content').innerHTML='<div class="notice">Configura config.js con los datos públicos del proyecto Supabase y ejecuta los SQL del paquete.</div>';return}await({catalog,bookings,reviews,contact,history}[view]||catalog)()}catch(e){$('content').innerHTML=`<div class="notice">${esc(e.message)}</div>`}}
async function cartView(){modal('Carrito',`<div>${cart.map(x=>`<p>${esc(x.name)} × ${x.quantity} — ${money(x.price*x.quantity)}</p>`).join('')}</div><h3>Total ${money(cart.reduce((s,x)=>s+x.price*x.quantity,0))}</h3><div class="fields"><label>Nombre<input id="buyerName"></label><label>Teléfono<input id="buyerPhone"></label><label>Notas<input id="buyerNotes"></label></div><button id="placeOrder">Crear pedido</button>`);$('placeOrder').onclick=async()=>{if(!session)return account();const {data,error}=await db.rpc('create_order',{p_items:cart.map(x=>({product_id:x.id,quantity:x.quantity})),p_contact_name:$('buyerName').value,p_contact_phone:$('buyerPhone').value,p_delivery_notes:$('buyerNotes').value});if(error)toast(error.message);else{cart=[];$('cartCount').textContent='0';hideModal();toast('Pedido creado '+data)}}}
const safeField=(value,type)=>type==='json'?JSON.stringify(value||{},null,2):value??'';
function control(k,t,val){const id='fld_'+k;if(t==='check')return `<label><span>${esc(k)}</span><input id="${id}" type="checkbox" ${val?'checked':''}></label>`;if(t==='icons')return `<label>${esc(k)}<select id="${id}">${ICONS.map(v=>`<option ${val===v?'selected':''} value="${esc(v)}">${esc(v)}</option>`).join('')}</select></label>`;if(t==='theme')return `<label>${esc(k)}<select id="${id}"><option value="dark">Oscuro</option><option value="light">Claro</option></select></label>`;if(t==='textarea'||t==='json')return `<label>${esc(k)}<textarea id="${id}" rows="4">${esc(safeField(val,t))}</textarea></label>`;return `<label>${esc(k)}<input id="${id}" type="${t==='number'?'number':t}" value="${esc(val??'')}" ${t==='number'?'step="any"':''}></label>`}
function formValues(spec){const out={};for(const [k,t] of Object.entries(spec)){const el=$('fld_'+k);if(t==='check')out[k]=el.checked;else if(t==='number')out[k]=el.value===''?null:Number(el.value);else if(t==='json')out[k]=JSON.parse(el.value||'{}');else if(t==='datetime-local')out[k]=el.value?new Date(el.value).toISOString():null;else out[k]=el.value;}return out}
async function adminOpen(){if(!admin){toast('No tienes acceso de administración');return}modal('Administración VibraErótica',`<div class="admin-layout"><nav class="nav" id="adminNav"></nav><div id="adminPage" class="panel"></div></div>`);$('modal').querySelector('.window').classList.add('wide');$('adminNav').innerHTML=`<button data-panel="dashboard">📊 Dashboard</button>`+Object.entries(schemas).map(([k,v])=>`<button data-panel="${k}">${esc(v.title)}</button>`).join('')+`<button data-panel="map">📍 Pin y mapa</button><button data-panel="links">📎 Productos ↔ profesionales</button>`;$('adminNav').querySelectorAll('button').forEach(b=>b.onclick=()=>adminPage(b.dataset.panel));adminPage('dashboard')}
async function adminPage(key){const host=$('adminPage');host.innerHTML='<p>Cargando…</p>';try{if(key==='dashboard'){const tables=['products','orders','reservations','reviews','payment_proofs'];const counts=await Promise.all(tables.map(t=>db.from(t).select('id',{count:'exact',head:true})));host.innerHTML='<h2>Dashboard</h2><div class="grid">'+tables.map((t,i)=>`<div class="card"><p>${esc(t)}</p><strong class="stat">${counts[i].count??'—'}</strong></div>`).join('')+'</div><p class="muted">Los movimientos reales se guardan en Supabase. No se muestran módulos de reparto ni calculadora de viajes.</p>';return}
 if(key==='map')return mapEditor();if(key==='links')return relationEditor();const conf=schemas[key];if(!conf)return;
 const data=await query(key,'*',300);host.innerHTML=`<div class="topline"><h2>${esc(conf.title)}</h2>${conf.form?`<button id="newRecord">+ Nuevo / editar</button>`:''}</div><div class="tablewrap"><table><thead><tr>${(conf.cols||Object.keys(conf.form)).map(f=>`<th>${esc(f)}</th>`).join('')}<th>Acciones</th></tr></thead><tbody>${data.map(row=>`<tr>${(conf.cols||Object.keys(conf.form)).map(f=>`<td>${esc(typeof row[f]==='object'?JSON.stringify(row[f]):row[f])}</td>`).join('')}<td>${conf.form?`<button class="secondary" data-edit="${esc(row.id??row.key??row.user_id)}">Editar</button>`:''}${key==='payment_proofs'?`<button data-review="${row.id}" data-action="approve_proof">Aprobar</button><button data-review="${row.id}" data-action="reject_proof">Rechazar</button>`:''}${key==='reviews'?`<button data-review="${row.id}" data-action="publish_review">Publicar</button><button data-review="${row.id}" data-action="reject_review">Rechazar</button>`:''}${key==='orders'||key==='reservations'?`<button data-review="${row.id}" data-action="confirm_${key==='orders'?'order':'reservation'}">Confirmar</button><button data-review="${row.id}" data-action="cancel_${key==='orders'?'order':'reservation'}">Cancelar</button>`:''}${key==='conversations'?`<button data-chat="${row.id}">Chat</button>`:''}</td></tr>`).join('')}</tbody></table></div>`;
 if(conf.form){$('newRecord').onclick=()=>adminEditor(key,conf.singleton?data[0]:null);host.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>adminEditor(key,data.find(r=>String(r.id??r.key??r.user_id)===b.dataset.edit)))}host.querySelectorAll('[data-review]').forEach(b=>b.onclick=async()=>{if(!confirm('¿Confirmar acción?'))return;await edge(b.dataset.action,b.dataset.review);adminPage(key)});host.querySelectorAll('[data-chat]').forEach(b=>b.onclick=()=>chatView(b.dataset.chat));
 }catch(e){host.innerHTML=`<div class="notice">${esc(e.message)}. Comprueba que ejecutaste los SQL 01 a 04 en el proyecto correcto.</div>`}}
async function adminEditor(table,row){const conf=schemas[table],host=$('adminPage');editing=row||null;let options={};if(conf.form.category_id==='categories'){options.category_id=await query('categories')};host.innerHTML=`<h2>${row?'Editar':'Nuevo'} · ${esc(conf.title)}</h2><div class="fields">${Object.entries(conf.form).map(([key,type])=>type==='categories'?`<label>${key}<select id="fld_${key}"><option value="">Sin categoría</option>${options.category_id.map(x=>`<option value="${x.id}" ${row?.[key]===x.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label>`:control(key,type,row?.[key])).join('')}</div><div class="row"><button id="saveRecord">Guardar</button><button class="secondary" id="backRecord">Volver</button></div><div id="mediaEditor"></div>`;
 $('backRecord').onclick=()=>adminPage(table);$('saveRecord').onclick=async()=>{try{let data=formValues(conf.form);if(table==='coupons')data.code=data.code.toUpperCase().trim();if(table==='site_options'&&!row)data.key=data.key.trim();if(table==='brand_settings'||table==='business_settings'||table==='ticket_settings')data.id=1;const filter=row?.id?{id:row.id}:row?.key?{key:row.key}:null;let req=filter?db.from(table).update(data).eq(Object.keys(filter)[0],Object.values(filter)[0]):db.from(table).insert(data);let r=await req.select().single();if(r.error)throw r.error;toast('Guardado correctamente');adminEditor(table,r.data)}catch(e){toast(e.message)}};
 if(conf.media&&row?.id){const target=table==='products'?'product_media':'practitioner_media',foreign=table==='products'?'product_id':'practitioner_id';const media=await query(target);const mine=media.filter(x=>x[foreign]===row.id);$('mediaEditor').innerHTML=`<hr><h3>Galería: múltiples fotografías y videos</h3>${productGallery(mine)}<div class="fields"><label>Agregar imágenes y videos<input id="filesMedia" type="file" accept="image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm" multiple></label></div><button id="uploadMedia">Subir archivos</button><div id="uploadResult" class="muted"></div>`;$('uploadMedia').onclick=async()=>{const files=Array.from($('filesMedia').files||[]);if(!files.length)return toast('Selecciona archivos');const results=[];for(const file of files){try{const kind=file.type.startsWith('video/')?'video':'image',name=file.name.replace(/[^a-z0-9_.-]/gi,'_'),path=(table==='products'?row.id:`practitioners/${row.id}`)+'/'+crypto.randomUUID()+'-'+name;const upload=await db.storage.from('catalog-media').upload(path,file,{contentType:file.type});if(upload.error)throw upload.error;const ins=await db.from(target).insert({[foreign]:row.id,object_path:path,media_type:kind,sort_order:mine.length+results.length});if(ins.error)throw ins.error;results.push(file.name)}catch(e){toast(`${file.name}: ${e.message}`)}}$('uploadResult').textContent=`Cargados ${results.length}/${files.length}`;adminEditor(table,row)}}
}
async function edge(action,id){if(!db||!session)throw Error('Inicia sesión');const r=await db.functions.invoke(C.edgeFunction||'admin-actions',{body:{action,id}});if(r.error)throw r.error;if(r.data?.error)throw Error(r.data.error);toast('Acción realizada')}
async function chatView(id){const msgs=await query('conversation_messages','*',500),host=$('adminPage');host.innerHTML=`<h2>Conversación</h2><div class="panel">${msgs.filter(x=>x.conversation_id===id).map(m=>`<p>${esc(m.body)} <small class="muted">${esc(m.created_at)}</small></p>`).join('')}</div><textarea id="chatText" placeholder="Responder"></textarea><p><button id="chatSend">Enviar mensaje</button></p>`;$('chatSend').onclick=async()=>{const r=await db.from('conversation_messages').insert({conversation_id:id,sender_id:session.user.id,body:$('chatText').value});if(r.error)toast(r.error.message);else chatView(id)}}
async function relationEditor(){const [people,services,durations]=await Promise.all([query('practitioners'),query('services'),query('service_durations')]);$('adminPage').innerHTML=`<h2>Servicios de cada masajista y duraciones</h2><div class="fields"><label>Masajista<select id="relationPerson">${people.map(x=>`<option value="${x.id}">${esc(x.display_name)}</option>`)}</select></label><label>Servicio<select id="relationSvc">${services.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`)}</select></label><label>Duración (minutos)<input type="number" id="duration" value="60" step="15"></label></div><div class="row"><button id="linkService">Asignar servicio a masajista</button><button id="addDuration">Añadir duración válida</button></div><p>Duraciones registradas: ${durations.map(d=>esc(d.minutes)+' min').join(', ')}</p>`;$('linkService').onclick=async()=>{const r=await db.from('practitioner_services').upsert({practitioner_id:$('relationPerson').value,service_id:$('relationSvc').value});toast(r.error?.message||'Asignado')};$('addDuration').onclick=async()=>{const r=await db.from('service_durations').upsert({service_id:$('relationSvc').value,minutes:+$('duration').value});toast(r.error?.message||'Duración agregada')}}
async function mapEditor(){const options=await query('site_options');const r=options.find(x=>x.key==='map')?.value||{};$('adminPage').innerHTML=`<h2>Pin y mapa del establecimiento</h2><p>Los iconos son configurables. El estilo CARTO predeterminado usa teselas públicas; para mapas premium configura tu token autorizado en la integración correspondiente.</p><div class="fields"><label>Latitud<input id="mapLat" type="number" step="any" value="${r.lat??19.1738}"></label><label>Longitud<input id="mapLng" type="number" step="any" value="${r.lng??-96.1342}"></label><label>Zoom<input id="mapZoom" type="number" value="${r.zoom??13}"></label><label>Pin<select id="mapPin">${ICONS.map(x=>`<option ${x===r.pin?'selected':''}>${esc(x)}</option>`).join('')}</select></label><label>Color del pin<input id="pinColor" type="color" value="${r.pin_color||'#ee3e81'}"></label><label>Nombre<input id="pinLabel" value="${esc(r.label||'VibraErótica')}"></label><label>Plantilla CARTO<select id="styleMap"><option value="dark_all">Oscuro</option><option value="light_all">Claro</option><option value="voyager">Voyager</option></select></label></div><button id="saveMap">Guardar mapa y pin</button>`;$('styleMap').value=(r.style||'').match(/cartocdn.com\/(.*?)\//)?.[1]||'dark_all';$('saveMap').onclick=async()=>{const value={lat:+$('mapLat').value,lng:+$('mapLng').value,zoom:+$('mapZoom').value,pin:$('mapPin').value,pin_color:$('pinColor').value,label:$('pinLabel').value,style:`https://{s}.basemaps.cartocdn.com/${$('styleMap').value}/{z}/{x}/{y}{r}.png`};const x=await db.from('site_options').upsert({key:'map',value});toast(x.error?.message||'Ubicación guardada')}}
$('modalClose').onclick=()=>{hideModal();$('modal').querySelector('.window').classList.remove('wide')};$('accountBtn').onclick=account;$('adminBtn').onclick=adminOpen;$('cartBtn').onclick=cartView;$('notifyBtn').onclick=async()=>{const r=await query('site_notifications');modal('Notificaciones',r.map(x=>`<p>${esc(x.title)}: ${esc(x.body)}</p>`).join('')||'Sin notificaciones')};$('aboutBtn').onclick=()=>show('contact');$('theme').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('vibra-theme',document.body.classList.contains('light')?'light':'dark')};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));if(localStorage.getItem('vibra-theme')==='light')document.body.classList.add('light');if(db){db.auth.onAuthStateChange(()=>setTimeout(()=>authUpdate().catch(e=>console.warn(e)),0));authUpdate().then(()=>show('catalog'))}else show('catalog');
